apiVersion: v1
kind: ConfigMap
metadata:
  name: unicorn-spring-ai-agent-config
data:
  application.properties: |
    spring.application.name=unicorn-spring-ai-agent

    logging.level.org.springframework.ai=DEBUG

    # Amazon Bedrock Configuration
    spring.ai.bedrock.converse.chat.options.model=anthropic.claude-3-sonnet-20240229-v1:0

    # Thymeleaf Configuration
    spring.thymeleaf.cache=false
    spring.thymeleaf.prefix=classpath:/templates/
    spring.thymeleaf.suffix=.html

    # RAG properties
    spring.ai.model.embedding=bedrock-titan
    spring.ai.bedrock.titan.embedding.model=amazon.titan-embed-text-v2:0
    spring.ai.bedrock.titan.embedding.input-type=text
